pipeline {
    agent any

    stages {
        stage("git clone") {
            steps {
            git branch: 'main', credentialsId: 'Jagadeesh', url: 'https://github.com/Jagadeesh-Reddy0/Practice-Project.git'
            echo "completed"

          }
        }
        
        stage ("terraform init") {
            steps {
                echo "terraform init" 
            }
        }
        
        stage ("terraform Action") {
            steps {
                echo "Terraform action is --> ${action}"
                echo "terraform ${action} --auto-approve1"
           }
        }
    }
}
